# Various ways to create tensors in tensorflow

loading Tensorflow and resetting the computational graph

In [1]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

# start a graph session

In [2]:
sess = tf.Session()   #note:Session

# creating tensors

generate 0 matrix

In [19]:
a = tf.Variable(tf.zeros([3,3]))
b = tf.zeros([3,4])
sess.run(a.initializer)
sess.run(a)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [21]:
row_dim = 2
col_dim = 3
zero_var = tf.Variable(tf.zeros([row_dim, col_dim]))
ones_var = tf.Variable(tf.ones([row_dim, col_dim]))
sess.run(zero_var.initializer)
sess.run(ones_var.initializer)
print(sess.run(zero_var))
print(sess.run(ones_var))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


# Creating Tensors Based on Other Tensor's Shape

In [25]:
zero_similar = tf.zeros_like(zero_var)
ones_similar = tf.ones_like(ones_var)

print(sess.run(ones_similar))
print(sess.run(zero_similar))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


# filling a tensor with a constant

In [29]:
c = tf.fill([3,3],3)
sess.run(c)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

another way to create a constant tensor

In [30]:
d = tf.Variable(tf.fill([3,4],5))
sess.run(d.initializer)
print(sess.run(d))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


create a variable from an array or list of constants

In [31]:
e = tf.constant([1,2,3,5,6,4])
f = tf.constant(4,shape=(3,5))
print(sess.run(e))
print(sess.run(f))

[1 2 3 5 6 4]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


# Creating Tensors Based on Sequences and Ranges

In [32]:
# Linspace in TensorFlow
linear_var = tf.Variable(tf.linspace(start=0.0, stop=1.0, num=3)) # Generates [0.0, 0.5, 1.0] includes the end

# Range in TensorFlow
sequence_var = tf.Variable(tf.range(start=6, limit=15, delta=3)) # Generates [6, 9, 12] doesn't include the end

sess.run(linear_var.initializer)
sess.run(sequence_var.initializer)

print(sess.run(linear_var))
print(sess.run(sequence_var))

[0.  0.5 1. ]
[ 6  9 12]


# Create random number tensors

In [34]:
var1 = tf.random_normal([3,3],mean = 3,stddev = 1.0)
var2 = tf.random_uniform([3,3],minval = 0,maxval = 5)

print(sess.run(var1))
print(sess.run(var2))

[[2.8967178 4.5267334 3.2571588]
 [2.6479166 3.2943234 3.5831392]
 [4.164553  2.4502497 5.1522493]]
[[3.0606425  1.8715996  0.15938699]
 [3.6831183  0.38983226 1.2611938 ]
 [3.1016982  3.495111   1.229195  ]]


# Visualizing the Variable Creation in TensorBoard

In [36]:
# Reset graph
ops.reset_default_graph()

# Start a graph session
sess = tf.Session()

# Create variable
my_var = tf.Variable(tf.zeros([1,20]))

# Add summaries to tensorboard
merged = tf.summary.merge_all()

# Initialize graph writer:
writer = tf.summary.FileWriter("/tmp/variable_logs", graph=sess.graph)

# Initialize operation
initialize_op = tf.global_variables_initializer()

# Run initialization of variable
sess.run(initialize_op)