# Matrices and Matrix Operations

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [2]:
sess = tf.Session()

# Declaring matrice

Identify Matrixs:

In [4]:
identify_matrix = tf.diag([2,2,2])
sess.run(identify_matrix)

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])

2×3 random constant matrix:

In [5]:
a = tf.truncated_normal([2,3])
sess.run(a)

array([[ 0.77767223,  1.0479395 ,  1.0434355 ],
       [ 0.6238146 , -0.90122515, -1.1457112 ]], dtype=float32)

In [6]:
b = tf.fill([2,3],2)
sess.run(b)

array([[2, 2, 2],
       [2, 2, 2]])

In [8]:
c= tf.random_uniform([2,3])
sess.run(c)

array([[0.26907778, 0.88008845, 0.00891924],
       [0.6336533 , 0.01819634, 0.95521426]], dtype=float32)

Create matrix from np array:

In [9]:
d = tf.convert_to_tensor(np.array([[1,2,3],[2,4,5],[-8,-4,0]]))
sess.run(d)

array([[ 1,  2,  3],
       [ 2,  4,  5],
       [-8, -4,  0]])

# Matrix Operations

Matrix addition/subtraction:

In [12]:
sess.run(a+c)

array([[1.617408  , 1.0232582 , 0.73902655],
       [1.1169031 , 1.7929136 , 1.7225213 ]], dtype=float32)

Matrix Multiplication:

In [13]:
sess.run(tf.matmul(b,identify_matrix))

array([[4, 4, 4],
       [4, 4, 4]])

In [14]:
print(sess.run(tf.transpose(c)))

[[0.8103888  0.8824656 ]
 [0.12459636 0.37795866]
 [0.92494655 0.4640169 ]]


Cholesky Decomposition